# Atelier1 : Text Mining/NLP



# 1.	Objectif 


# 2.	Outils et environnement de travail 


In [1]:
pip install spacy

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install pywsd

Note: you may need to restart the kernel to use updated packages.


In [3]:
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ismail\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ismail\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\ismail\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [4]:

nltk.download('maxent_ne_chunker')
nltk.download('words')

[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     C:\Users\ismail\AppData\Roaming\nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to
[nltk_data]     C:\Users\ismail\AppData\Roaming\nltk_data...
[nltk_data]   Package words is already up-to-date!


True

# 3.	Les bases de la NLP

## 3.1.	Segmentation (Tokenization)

In [11]:
from nltk.tokenize import sent_tokenize, word_tokenize
data="Hello, i am very happy to meet you. I created this course for you. Good by!"
doc1='Computer science is the study of computers and computing concepts. It includes both hardware and software, as well as networking and the Internet'

sentences=sent_tokenize(data) #divise en phrase
print(sentences)
words=word_tokenize(data)#divise en word token
#print(words)

['Hello, i am very happy to meet you.', 'I created this course for you.', 'Good by!']


## 3.2.	Nettoyage(Cleaning) 


In [12]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
data="Hello, i am very happy to meet you. I created this course for you. Good by!"
word_tokens = [word.lower() for word in word_tokenize(data)]
data_clean = [word for word in word_tokens if (not word in set(stopwords.words('english')) and  word.isalpha())]
print(data_clean)
#un mot vide (ou stop word, en anglais) est un mot qui est tellement commun qu'il est inutile de l'indexer ou de l'utiliser dans une recherche. En français, des mots vides évidents pourraient être « le », « la », « de », « du », « ce »…

['hello', 'happy', 'meet', 'created', 'course', 'good']


## 3.3.	Racinisation(Stemming)

In [13]:
from nltk.stem import PorterStemmer,SnowballStemmer
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
#stemmer=SnowballStemmer('french')
stemmer=PorterStemmer()
data="Le big data  « grosses données » en anglais,les mégadonnées ou les données massives, " \
     "désigne les ressources d’informations dont les caractéristiques en termes de volume," \
     " de vélocité et de variété imposent l’utilisation de technologies et de méthodes analytiques " \
     "particulières pour générer de la valeur, et qui dépassent en général les capacités " \
     "d'une seule et unique machine et nécessitent des traitements parallélisés"
word_tokens = [word.lower() for word in word_tokenize(data)]

for i in range(len(word_tokens)):
    words=[stemmer.stem(word) for word in word_tokens if (not word in set(stopwords.words('french')) and  word.isalpha())]
print(words)

['big', 'data', 'gross', 'donné', 'anglai', 'mégadonné', 'donné', 'massiv', 'désign', 'ressourc', 'inform', 'dont', 'caractéristiqu', 'term', 'volum', 'vélocité', 'variété', 'impos', 'utilis', 'technolog', 'méthode', 'analytiqu', 'particulièr', 'générer', 'valeur', 'dépassent', 'général', 'capacité', 'seul', 'uniqu', 'machin', 'nécessit', 'traitement', 'parallélisé']


In [14]:
set(words)

{'analytiqu',
 'anglai',
 'big',
 'capacité',
 'caractéristiqu',
 'data',
 'donné',
 'dont',
 'dépassent',
 'désign',
 'gross',
 'général',
 'générer',
 'impos',
 'inform',
 'machin',
 'massiv',
 'mégadonné',
 'méthode',
 'nécessit',
 'parallélisé',
 'particulièr',
 'ressourc',
 'seul',
 'technolog',
 'term',
 'traitement',
 'uniqu',
 'utilis',
 'valeur',
 'variété',
 'volum',
 'vélocité'}

In [15]:
from nltk.stem import PorterStemmer,SnowballStemmer
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
stemmer=SnowballStemmer('french')
#stemmer=PorterStemmer()
data="Le big data  « grosses données » en anglais,les mégadonnées ou les données massives, " \
     "désigne les ressources d’informations dont les caractéristiques en termes de volume," \
     " de vélocité et de variété imposent l’utilisation de technologies et de méthodes analytiques " \
     "particulières pour générer de la valeur, et qui dépassent en général les capacités " \
     "d'une seule et unique machine et nécessitent des traitements parallélisés"
word_tokens = [word.lower() for word in word_tokenize(data)]

for i in range(len(words)):
    words=[stemmer.stem(word) for word in word_tokens if (not word in set(stopwords.words('french')) and  word.isalpha())]
print(words)

['big', 'dat', 'gross', 'don', 'anglais', 'mégadon', 'don', 'massiv', 'désign', 'ressourc', 'inform', 'dont', 'caractérist', 'term', 'volum', 'véloc', 'variet', 'imposent', 'utilis', 'technolog', 'méthod', 'analyt', 'particuli', 'géner', 'valeur', 'dep', 'général', 'capac', 'seul', 'uniqu', 'machin', 'nécessitent', 'trait', 'parallélis']


## 3.4.	Lemmatisation

In [16]:
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

lemmmatizer=WordNetLemmatizer()
data="Big data is a field that treats ways to analyze, systematically extract information from," \
     " or otherwise deal with data sets that are too large or complex to be dealt with by traditional" \
     " data-processing application software. Data with many cases (rows) offer greater statistical power," \
     " while data with higher complexity (more attributes or columns) " \
     "may lead to a higher false discovery rate. "
words = word_tokenize(data)
words = [lemmmatizer.lemmatize(word.lower()) for word in words if(not word in set(stopwords.words('english')) and  word.isalpha())]
print(words)

['big', 'data', 'field', 'treat', 'way', 'analyze', 'systematically', 'extract', 'information', 'otherwise', 'deal', 'data', 'set', 'large', 'complex', 'dealt', 'traditional', 'application', 'software', 'data', 'many', 'case', 'row', 'offer', 'greater', 'statistical', 'power', 'data', 'higher', 'complexity', 'attribute', 'column', 'may', 'lead', 'higher', 'false', 'discovery', 'rate']


## 3.5.	POS-Tagging

In [17]:
import nltk
from nltk.tokenize import word_tokenize
data="Big data is a field that treats ways to analyze, systematically extract information from," \
     " or otherwise deal with data sets that are too large or complex to be dealt with by traditional" \
     " data-processing application software. Data with many cases (rows) offer greater statistical power," \
     " while data with higher complexity (more attributes or columns) " \
     "may lead to a higher false discovery rate. "
words=word_tokenize(data)
print(nltk.pos_tag(words))

[('Big', 'NNP'), ('data', 'NN'), ('is', 'VBZ'), ('a', 'DT'), ('field', 'NN'), ('that', 'WDT'), ('treats', 'VBZ'), ('ways', 'NNS'), ('to', 'TO'), ('analyze', 'VB'), (',', ','), ('systematically', 'RB'), ('extract', 'JJ'), ('information', 'NN'), ('from', 'IN'), (',', ','), ('or', 'CC'), ('otherwise', 'RB'), ('deal', 'NN'), ('with', 'IN'), ('data', 'NNS'), ('sets', 'NNS'), ('that', 'WDT'), ('are', 'VBP'), ('too', 'RB'), ('large', 'JJ'), ('or', 'CC'), ('complex', 'JJ'), ('to', 'TO'), ('be', 'VB'), ('dealt', 'VBN'), ('with', 'IN'), ('by', 'IN'), ('traditional', 'JJ'), ('data-processing', 'JJ'), ('application', 'NN'), ('software', 'NN'), ('.', '.'), ('Data', 'NNP'), ('with', 'IN'), ('many', 'JJ'), ('cases', 'NNS'), ('(', '('), ('rows', 'NNS'), (')', ')'), ('offer', 'VBP'), ('greater', 'JJR'), ('statistical', 'JJ'), ('power', 'NN'), (',', ','), ('while', 'IN'), ('data', 'NNS'), ('with', 'IN'), ('higher', 'JJR'), ('complexity', 'NN'), ('(', '('), ('more', 'RBR'), ('attributes', 'NNS'), ('or', 

In [18]:
import nltk
from nltk.tokenize import sent_tokenize
data="Big data is a field that treats ways to analyze, systematically extract information from," \
     " or otherwise deal with data sets that are too large or complex to be dealt with by traditional" \
     " data-processing application software. Data with many cases (rows) offer greater statistical power," \
     " while data with higher complexity (more attributes or columns) " \
     "may lead to a higher false discovery rate. "


sentences=sent_tokenize(data)

list=[]
for sentence in sentences:
    list.append(word_tokenize(sentence))
    
print(nltk.pos_tag_sents(list))

[[('Big', 'NNP'), ('data', 'NN'), ('is', 'VBZ'), ('a', 'DT'), ('field', 'NN'), ('that', 'WDT'), ('treats', 'VBZ'), ('ways', 'NNS'), ('to', 'TO'), ('analyze', 'VB'), (',', ','), ('systematically', 'RB'), ('extract', 'JJ'), ('information', 'NN'), ('from', 'IN'), (',', ','), ('or', 'CC'), ('otherwise', 'RB'), ('deal', 'NN'), ('with', 'IN'), ('data', 'NNS'), ('sets', 'NNS'), ('that', 'WDT'), ('are', 'VBP'), ('too', 'RB'), ('large', 'JJ'), ('or', 'CC'), ('complex', 'JJ'), ('to', 'TO'), ('be', 'VB'), ('dealt', 'VBN'), ('with', 'IN'), ('by', 'IN'), ('traditional', 'JJ'), ('data-processing', 'JJ'), ('application', 'NN'), ('software', 'NN'), ('.', '.')], [('Data', 'NNP'), ('with', 'IN'), ('many', 'JJ'), ('cases', 'NNS'), ('(', '('), ('rows', 'NNS'), (')', ')'), ('offer', 'VBP'), ('greater', 'JJR'), ('statistical', 'JJ'), ('power', 'NN'), (',', ','), ('while', 'IN'), ('data', 'NNS'), ('with', 'IN'), ('higher', 'JJR'), ('complexity', 'NN'), ('(', '('), ('more', 'RBR'), ('attributes', 'NNS'), ('or

In [19]:
nltk.pos_tag_sents(list)[0]

[('Big', 'NNP'),
 ('data', 'NN'),
 ('is', 'VBZ'),
 ('a', 'DT'),
 ('field', 'NN'),
 ('that', 'WDT'),
 ('treats', 'VBZ'),
 ('ways', 'NNS'),
 ('to', 'TO'),
 ('analyze', 'VB'),
 (',', ','),
 ('systematically', 'RB'),
 ('extract', 'JJ'),
 ('information', 'NN'),
 ('from', 'IN'),
 (',', ','),
 ('or', 'CC'),
 ('otherwise', 'RB'),
 ('deal', 'NN'),
 ('with', 'IN'),
 ('data', 'NNS'),
 ('sets', 'NNS'),
 ('that', 'WDT'),
 ('are', 'VBP'),
 ('too', 'RB'),
 ('large', 'JJ'),
 ('or', 'CC'),
 ('complex', 'JJ'),
 ('to', 'TO'),
 ('be', 'VB'),
 ('dealt', 'VBN'),
 ('with', 'IN'),
 ('by', 'IN'),
 ('traditional', 'JJ'),
 ('data-processing', 'JJ'),
 ('application', 'NN'),
 ('software', 'NN'),
 ('.', '.')]

In [20]:
import nltk
nltk.download('brown')
from nltk.corpus import brown #The Brown Corpus was the first million-word electronic corpus of English
from nltk.tag import UnigramTagger
from nltk.tokenize import word_tokenize

brown_tagged_sents = brown.tagged_sents(categories='news')
size = int(len(brown_tagged_sents) * 0.9)
train_sents = brown_tagged_sents[:size]
test_sents = brown_tagged_sents[size:]
unigram_tagger = nltk.UnigramTagger(train_sents)
print(unigram_tagger.evaluate(test_sents))

data="Big data is a field that treats ways to analyze, systematically extract information from," \
     " or otherwise deal with data sets that are too large or complex to be dealt with by traditional" \
     " data-processing application software. Data with many cases (rows) offer greater statistical power," \
     " while data with higher complexity (more attributes or columns) " \
     "may lead to a higher false discovery rate. "
print(unigram_tagger.tag(word_tokenize(data)))

[nltk_data] Downloading package brown to
[nltk_data]     C:\Users\ismail\AppData\Roaming\nltk_data...
[nltk_data]   Package brown is already up-to-date!


0.8121200039868434
[('Big', 'JJ-TL'), ('data', 'NN'), ('is', 'BEZ'), ('a', 'AT'), ('field', 'NN'), ('that', 'CS'), ('treats', None), ('ways', 'NNS'), ('to', 'TO'), ('analyze', None), (',', ','), ('systematically', None), ('extract', None), ('information', 'NN'), ('from', 'IN'), (',', ','), ('or', 'CC'), ('otherwise', 'RB'), ('deal', 'VB'), ('with', 'IN'), ('data', 'NN'), ('sets', 'VBZ-HL'), ('that', 'CS'), ('are', 'BER'), ('too', 'QL'), ('large', 'JJ'), ('or', 'CC'), ('complex', 'JJ'), ('to', 'TO'), ('be', 'BE'), ('dealt', 'VBD'), ('with', 'IN'), ('by', 'IN'), ('traditional', 'JJ'), ('data-processing', None), ('application', 'NN'), ('software', None), ('.', '.'), ('Data', None), ('with', 'IN'), ('many', 'AP'), ('cases', 'NNS'), ('(', '('), ('rows', None), (')', ')'), ('offer', 'VB'), ('greater', 'JJR'), ('statistical', 'JJ'), ('power', 'NN'), (',', ','), ('while', 'CS'), ('data', 'NN'), ('with', 'IN'), ('higher', 'JJR'), ('complexity', 'NN'), ('(', '('), ('more', 'AP'), ('attributes', 

In [21]:
brown_tagged_sents = brown.tagged_sents(categories='news')
size = int(len(brown_tagged_sents) * 0.9)
train_sents = brown_tagged_sents[:size]
test_sents = brown_tagged_sents[size:]
bigram_tagger = nltk.BigramTagger(train_sents)
print(bigram_tagger.evaluate(test_sents))
data="Big data is a field that treats ways to analyze, systematically extract information from," \
     " or otherwise deal with data sets that are too large or complex to be dealt with by traditional" \
     " data-processing application software. Data with many cases (rows) offer greater statistical power," \
     " while data with higher complexity (more attributes or columns) " \
     "may lead to a higher false discovery rate. "
print(bigram_tagger.tag(word_tokenize(data.lower()))) #bigram= on traite deux termes par deux

0.10206319146815508
[('big', None), ('data', None), ('is', None), ('a', None), ('field', None), ('that', None), ('treats', None), ('ways', None), ('to', None), ('analyze', None), (',', None), ('systematically', None), ('extract', None), ('information', None), ('from', None), (',', None), ('or', None), ('otherwise', None), ('deal', None), ('with', None), ('data', None), ('sets', None), ('that', None), ('are', None), ('too', None), ('large', None), ('or', None), ('complex', None), ('to', None), ('be', None), ('dealt', None), ('with', None), ('by', None), ('traditional', None), ('data-processing', None), ('application', None), ('software', None), ('.', None), ('data', None), ('with', None), ('many', None), ('cases', None), ('(', None), ('rows', None), (')', None), ('offer', None), ('greater', None), ('statistical', None), ('power', None), (',', None), ('while', None), ('data', None), ('with', None), ('higher', None), ('complexity', None), ('(', None), ('more', None), ('attributes', None),

In [22]:
brown_tagged_sents = brown.tagged_sents(categories='news')

size = int(len(brown_tagged_sents) * 0.9)
train_sents = brown_tagged_sents[:size]
test_sents = brown_tagged_sents[size:]
t0 = nltk.DefaultTagger('NN')
t1 = nltk.UnigramTagger(train_sents, backoff=t0)
t2 = nltk.BigramTagger(train_sents, backoff=t1)
print(t2.evaluate(test_sents))
data="Big data is a field that treats ways to analyze, systematically extract information from," \
     " or otherwise deal with data sets that are too large or complex to be dealt with by traditional" \
     " data-processing application software. Data with many cases (rows) offer greater statistical power," \
     " while data with higher complexity (more attributes or columns) " \
     "may lead to a higher false discovery rate. "
print(t2.tag(word_tokenize(data)))


0.8452108043456593
[('Big', 'JJ-TL'), ('data', 'NN'), ('is', 'BEZ'), ('a', 'AT'), ('field', 'NN'), ('that', 'CS'), ('treats', 'NN'), ('ways', 'NNS'), ('to', 'TO'), ('analyze', 'NN'), (',', ','), ('systematically', 'NN'), ('extract', 'NN'), ('information', 'NN'), ('from', 'IN'), (',', ','), ('or', 'CC'), ('otherwise', 'RB'), ('deal', 'VB'), ('with', 'IN'), ('data', 'NN'), ('sets', 'VBZ-HL'), ('that', 'CS'), ('are', 'BER'), ('too', 'QL'), ('large', 'JJ'), ('or', 'CC'), ('complex', 'NN'), ('to', 'TO'), ('be', 'BE'), ('dealt', 'VBD'), ('with', 'IN'), ('by', 'IN'), ('traditional', 'JJ'), ('data-processing', 'NN'), ('application', 'NN'), ('software', 'NN'), ('.', '.'), ('Data', 'NN'), ('with', 'IN'), ('many', 'AP'), ('cases', 'NNS'), ('(', '('), ('rows', 'NN'), (')', ')'), ('offer', 'VB'), ('greater', 'JJR'), ('statistical', 'JJ'), ('power', 'NN'), (',', ','), ('while', 'CS'), ('data', 'NN'), ('with', 'IN'), ('higher', 'JJR'), ('complexity', 'NN'), ('(', '('), ('more', 'AP'), ('attributes', 

In [23]:
import os
java_path = "C:/Users/ismail/Downloads/sqldeveloper/jdk/jre/bin"
os.environ['JAVAHOME'] = java_path

In [24]:
import nltk
from nltk.tag.stanford import StanfordPOSTagger

data="Le big data  « grosses données » en anglais,les mégadonnées ou les données massives, " \
     "désigne les ressources d’informations dont les caractéristiques en termes de volume," \
     " de vélocité et de variété imposent l’utilisation de technologies et de méthodes analytiques " \
     "particulières pour générer de la valeur, et qui dépassent en général les capacités " \
     "d'une seule et unique machine et nécessitent des traitements parallélisés"
#root="/Users/rachad/Desktop/Labs/Labs Material/stanford-postagger-full-2020-11-17"
root="C:/Users/ismail/Desktop/stanford-postagger-full-2020-11-17"
stf = StanfordPOSTagger(root+'/models/french-ud.tagger',"C:/Users/ismail/Desktop/stanford-postagger-full-2020-11-17/stanford-postagger.jar",encoding='utf8')
tokens = nltk.word_tokenize(data) 
print(stf.tag(tokens))

[('Le', 'DET'), ('big', 'ADJ'), ('data', 'NOUN'), ('«', 'PUNCT'), ('grosses', 'ADJ'), ('données', 'NOUN'), ('»', 'PUNCT'), ('en', 'ADP'), ('anglais', 'NOUN'), (',', 'PUNCT'), ('les', 'DET'), ('mégadonnées', 'NOUN'), ('ou', 'CCONJ'), ('les', 'DET'), ('données', 'NOUN'), ('massives', 'ADJ'), (',', 'PUNCT'), ('désigne', 'VERB'), ('les', 'DET'), ('ressources', 'NOUN'), ('d', 'ADP'), ('’', 'NUM'), ('informations', 'NOUN'), ('dont', 'PRON'), ('les', 'DET'), ('caractéristiques', 'NOUN'), ('en', 'ADP'), ('termes', 'NOUN'), ('de', 'ADP'), ('volume', 'NOUN'), (',', 'PUNCT'), ('de', 'ADP'), ('vélocité', 'NOUN'), ('et', 'CCONJ'), ('de', 'ADP'), ('variété', 'NOUN'), ('imposent', 'VERB'), ('l', 'DET'), ('’', 'PUNCT'), ('utilisation', 'NOUN'), ('de', 'ADP'), ('technologies', 'NOUN'), ('et', 'CCONJ'), ('de', 'ADP'), ('méthodes', 'NOUN'), ('analytiques', 'ADJ'), ('particulières', 'ADJ'), ('pour', 'ADP'), ('générer', 'VERB'), ('de', 'ADP'), ('la', 'DET'), ('valeur', 'NOUN'), (',', 'PUNCT'), ('et', 'CCON

## 3.6.	NER (Named Entity Recognition)

In [25]:
import nltk
from nltk.tokenize import word_tokenize
data="William Henry Gates III (born October 28, 1955) is an American business magnate," \
     " software developer, and philanthropist. He is best known as the co-founder of Microsoft Corporation." \
     "During his career at Microsoft, Gates held the positions of chairman, " \
     "chief executive officer (CEO), president and chief software architect, " \
     "while also being the largest individual shareholder until May 2014. " \
     "He is one of the best-known entrepreneurs and pioneers of the microcomputer " \
     "revolution of the 1970s and 1980s."
words=word_tokenize(data)
print(nltk.ne_chunk(nltk.pos_tag(words)))


(S
  (PERSON William/NNP)
  (PERSON Henry/NNP Gates/NNP III/NNP)
  (/(
  born/JJ
  October/NNP
  28/CD
  ,/,
  1955/CD
  )/)
  is/VBZ
  an/DT
  (GPE American/JJ)
  business/NN
  magnate/NN
  ,/,
  software/NN
  developer/NN
  ,/,
  and/CC
  philanthropist/NN
  ./.
  He/PRP
  is/VBZ
  best/RB
  known/VBN
  as/IN
  the/DT
  co-founder/NN
  of/IN
  (ORGANIZATION Microsoft/NNP)
  Corporation.During/VBG
  his/PRP$
  career/NN
  at/IN
  (ORGANIZATION Microsoft/NNP)
  ,/,
  (PERSON Gates/NNP)
  held/VBD
  the/DT
  positions/NNS
  of/IN
  chairman/NN
  ,/,
  chief/JJ
  executive/NN
  officer/NN
  (/(
  (ORGANIZATION CEO/NNP)
  )/)
  ,/,
  president/NN
  and/CC
  chief/NN
  software/NN
  architect/NN
  ,/,
  while/IN
  also/RB
  being/VBG
  the/DT
  largest/JJS
  individual/JJ
  shareholder/NN
  until/IN
  May/NNP
  2014/CD
  ./.
  He/PRP
  is/VBZ
  one/CD
  of/IN
  the/DT
  best-known/JJ
  entrepreneurs/NNS
  and/CC
  pioneers/NNS
  of/IN
  the/DT
  microcomputer/NN
  revolution/NN
  of/IN
  t

## 3.7.	WSD

In [26]:
from nltk.corpus import wordnet
for sens in wordnet.synsets('break'):
    print(">>>",sens.definition())


>>> some abrupt occurrence that interrupts an ongoing activity
>>> an unexpected piece of good luck
>>> (geology) a crack in the earth's crust resulting from the displacement of one side with respect to the other
>>> a personal or social separation (as between opposing factions)
>>> a pause from doing something (as work)
>>> the act of breaking something
>>> a time interval during which there is a temporary cessation of something
>>> breaking of hard tissue such as bone
>>> the occurrence of breaking
>>> an abrupt change in the tone or register of the voice (as at puberty or due to emotion)
>>> the opening shot that scatters the balls in billiards or pool
>>> (tennis) a score consisting of winning a game when your opponent was serving
>>> an act of delaying or interrupting the continuity
>>> a sudden dash
>>> any frame in which a bowler fails to make a strike or spare
>>> an escape from jail
>>> terminate
>>> become separated into pieces or fragments
>>> render inoperable or ineffectiv

In [27]:
from nltk.wsd import lesk
from nltk.tokenize import word_tokenize
context= word_tokenize("I've just finished the first step of the competition. I need a little break to catch my breath")
print(lesk(context, 'break','n').definition())

(geology) a crack in the earth's crust resulting from the displacement of one side with respect to the other


In [28]:
pip install pywsd

Note: you may need to restart the kernel to use updated packages.


In [29]:
pip install wn==0.0.22

Note: you may need to restart the kernel to use updated packages.


In [30]:
# pip install pywsd
# pip install -U pywsd
#pip install wn==0.0.22
from pywsd.lesk import simple_lesk
sent = 'I went to the bank to deposit my money'
ambiguous = 'bank'
answer = simple_lesk(sent, ambiguous, pos='n')
print (answer)
print (answer.definition())
#It is based on the hypothesis that words used together 
#in text are related to each other and that the relation 
#can be observed in the definitions of the words and their senses.


Warming up PyWSD (takes ~10 secs)... 

Synset('depository_financial_institution.n.01')
a financial institution that accepts deposits and channels the money into lending activities


took 4.580479621887207 secs.


## 3.8.	Spacy

In [31]:
!pip install spacy
import spacy
nlp = spacy.load('fr_core_news_sm')
doc = nlp("Le big data  « grosses données » en anglais,les mégadonnées ou les données massives, " \
     "désigne les ressources d’informations dont les caractéristiques en termes de volume," \
     " de vélocité et de variété imposent l’utilisation de technologies et de méthodes analytiques " \
     "particulières pour générer de la valeur, et qui dépassent en général les capacités " \
     "d'une seule et unique machine et nécessitent des traitements parallélisés")

for token in doc:
    print("/token:",token.text, "/lemma:",token.lemma_, token.shape_, token.is_alpha, token.is_stop,"/POS:", token.tag_, "/PARS:", token.head, token.dep_, "/NER:", token.ent_iob_, token.ent_type_)

/token: Le /lemma: le Xx True True /POS: DET /PARS: big det /NER: O 
/token: big /lemma: big xxx True False /POS: NUM /PARS: data nummod /NER: O 
/token: data /lemma: data xxxx True False /POS: ADP /PARS: data ROOT /NER: O 
/token:   /lemma:     False False /POS: SPACE /PARS: data punct /NER: O 
/token: « /lemma: « « False False /POS: NOUN /PARS: « ROOT /NER: O 
/token: grosses /lemma: gros xxxx True False /POS: ADJ /PARS: données amod /NER: O 
/token: données /lemma: donnée xxxx True False /POS: NOUN /PARS: données ROOT /NER: O 
/token: » /lemma: » » False False /POS: PUNCT /PARS: données punct /NER: O 
/token: en /lemma: en xx True True /POS: ADP /PARS: anglais case /NER: O 
/token: anglais /lemma: anglais xxxx True False /POS: NOUN /PARS: données obl:mod /NER: O 
/token: , /lemma: , , False False /POS: PUNCT /PARS: désigne punct /NER: O 
/token: les /lemma: le xxx True True /POS: DET /PARS: mégadonnées det /NER: O 
/token: mégadonnées /lemma: mégadonnée xxxx True False /POS: NOUN /P

# 4.	Model représentatif d’un document

## 4.2. One-hot-vector

In [32]:
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.preprocessing import Binarizer

freq   = CountVectorizer()
corpus = ['This is the first document.','This is the second second document.','And the third one.','Is this the first document?']
corpus=[ sent.lower() for sent in corpus]
corpus = freq.fit_transform(corpus)
#print(corpus.toarray())
onehot = Binarizer()
corpus = onehot.fit_transform(corpus.toarray())
print(corpus)

[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 1 1 0 1]
 [1 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 0 1 0 1]]


## 4.1.	Beg-of-words

In [33]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
corpus = ['This is the first document.','This is the second second document.','And the third one.','Is this the first document?']
corpus=[ sent.lower() for sent in corpus]
X = vectorizer.fit_transform(corpus) #sparsy format
print(X.toarray()) # explicit matrix format
print(vectorizer.get_feature_names() ) #vocabulary as list of string
vectorizer.vocabulary_.get('document') #get column index of a specific term in the vocabulary
vectorizer.transform(['Something completely new.']).toarray()#apply the model to a new document

[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 2 1 0 1]
 [1 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 0 1 0 1]]
['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


array([[0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

## 4.2.	TF-IDF

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = ['This is the first document.','this is the second second Document.','And the third one.','Is this the first document?']
vectorizer = TfidfVectorizer()
X=vectorizer.fit_transform(corpus)
print(X.toarray())
print(vectorizer.get_feature_names() )

#NB: le vecteur tf-idf obtenu sera normalisé pour obtenir des valeurs entre 0 et 1.

[[0.         0.43877674 0.54197657 0.43877674 0.         0.
  0.35872874 0.         0.43877674]
 [0.         0.27230147 0.         0.27230147 0.         0.85322574
  0.22262429 0.         0.27230147]
 [0.55280532 0.         0.         0.         0.55280532 0.
  0.28847675 0.55280532 0.        ]
 [0.         0.43877674 0.54197657 0.43877674 0.         0.
  0.35872874 0.         0.43877674]]
['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


# 5.	Cas utilisations : Détection du Plagiarisme 

L’objectif de cet atelier est de détecter le pélagianisme à partir de wikipedia pendant la préparation des réponses à un certain nombre de questions sur des connaissances en informatique. Le dataset utilisé peut-être récupéré à partir du lien suivant :Cliquer <a href="https://ir.shef.ac.uk/cloughie/resources/plagiarism_corpus.html#Download" target="_blank">ICI</a> 

Pour ce faire, nous nous basant sur le calcul des similarités entre les réponses des candidats et les définitions exactes trouvées sur Wikipédia. Deux méthodes de calcul de similarité sont à utiliser, à savoir, la similarité syntaxique et la similarité sémantique.

**Recuperer le dataset
**Réaliser les différentes tâches de prétraitement.

In [35]:
import glob
files=glob.glob('C:/Users/ismail/Desktop/corpus/*')
f_pointers=[open(file,"r",encoding="utf8",errors='ignore') for file in files]
corpus=[f.read() for f in f_pointers]
#print(corpus)


In [36]:
##### print(len(corpus))
d=[]
for i in corpus:
    word_tokens = [word.lower() for word in word_tokenize(i)]
    words = [lemmmatizer.lemmatize(word.lower()) for word in word_tokens if(not word in set(stopwords.words('english')) and  word.isalpha())] 
    d.append(words)
print(len(d))
print(type(corpus[0]))

100
<class 'str'>


On aura besoin que de la lemmatization aprés avoir rendu le doc sous forme de token pour pouvoir faire la similarité syntaxique

## 5.1 similarité syntaxique 

In [37]:
from sklearn.metrics.pairwise import cosine_distances,euclidean_distances
tfidf_vectorizer = TfidfVectorizer()
corpus = ['This is the first document.','This is the second second document.','And the third one.','Is this the first document?']
tfidf_matrix = tfidf_vectorizer.fit_transform(corpus)
tfidf_matrix.shape

#compute similarity for first sentence with rest of the sentences
euclidean_distances(tfidf_matrix[0:1],tfidf_matrix)

array([[0.        , 1.05990529, 1.33904078, 0.        ]])

**Realiser la même chose en se basant sur les representations OHV et BOW?
**Comparer les performances des trois methodes en terme de temps d'execution et precision.  

## OHV

In [38]:
##
corpus = ['This is the first document.','This is the second second document.','And the third one.','Is this the first document?']
freq   = CountVectorizer()
c=[sent.lower() for sent in corpus]
cor = freq.fit_transform(corpus)

#compute similarity for first sentence with rest of the sentences
euclidean_distances(cor[0:1],cor)

array([[0.        , 2.23606798, 2.64575131, 0.        ]])

## BOW

In [39]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
corpus = ['This','This is the second second document.','And the third one.','Is this the first document?']
corpus=[ sent.lower() for sent in corpus]
X = vectorizer.fit_transform(corpus)
euclidean_distances(X[0:1],X)

array([[0.        , 2.64575131, 2.23606798, 2.        ]])

à mon avis le plus précis est le tfidf car il prend en considération meme la fréquence du terme dans
tous le corpus c'est ce qui fait de lui plus précis

Il existe d'autre methodes(orientées caractères) pour le calcule de la similarité syntaxique entre des documents courts (des phrases):

* Longest Common Sequence (LCS)
* Set features
* Word Order Similarity
* n-gram sentences 
* Jaro-Winkler
* ...

Cliquer <a href="http://www.iaeme.com/MasterAdmin/Journal_uploads/IJCET/VOLUME_9_ISSUE_5/IJCET_09_05_001.pdf" target="_blank">ICI</a> pour plus de details



## en utilisant la distance euclidienne on a:

In [40]:
import glob
files=glob.glob('C:/Users/ismail/Desktop/corpus/*')
f_pointers=[open(file,"r",encoding="utf8",errors='ignore') for file in files]
corpus=[f.read() for f in f_pointers]
print(files)


['C:/Users/ismail/Desktop/corpus\\g0pA_taska.txt', 'C:/Users/ismail/Desktop/corpus\\g0pA_taskb.txt', 'C:/Users/ismail/Desktop/corpus\\g0pA_taskc.txt', 'C:/Users/ismail/Desktop/corpus\\g0pA_taskd.txt', 'C:/Users/ismail/Desktop/corpus\\g0pA_taske.txt', 'C:/Users/ismail/Desktop/corpus\\g0pB_taska.txt', 'C:/Users/ismail/Desktop/corpus\\g0pB_taskb.txt', 'C:/Users/ismail/Desktop/corpus\\g0pB_taskc.txt', 'C:/Users/ismail/Desktop/corpus\\g0pB_taskd.txt', 'C:/Users/ismail/Desktop/corpus\\g0pB_taske.txt', 'C:/Users/ismail/Desktop/corpus\\g0pC_taska.txt', 'C:/Users/ismail/Desktop/corpus\\g0pC_taskb.txt', 'C:/Users/ismail/Desktop/corpus\\g0pC_taskc.txt', 'C:/Users/ismail/Desktop/corpus\\g0pC_taskd.txt', 'C:/Users/ismail/Desktop/corpus\\g0pC_taske.txt', 'C:/Users/ismail/Desktop/corpus\\g0pD_taska.txt', 'C:/Users/ismail/Desktop/corpus\\g0pD_taskb.txt', 'C:/Users/ismail/Desktop/corpus\\g0pD_taskc.txt', 'C:/Users/ismail/Desktop/corpus\\g0pD_taskd.txt', 'C:/Users/ismail/Desktop/corpus\\g0pD_taske.txt',

**Calculer les similarités syntaxiques entre les réponses des étudiants et les définitions trouvées sur wikipedia.


In [41]:
taska=[corpus[5*i] for i in range(19)]
taskb=[corpus[5*i+1] for i in range(19)]
taskc=[corpus[5*i+2] for i in range(19)]
taskd=[corpus[5*i+3] for i in range(19)]
taske=[corpus[5*i+4] for i in range(19)]

In [42]:
import pandas as pd
vectorizer = CountVectorizer()
task=corpus[95:]
#print(task)
tasks=[]
tasks.append(taska)
tasks.append(taskb)
tasks.append(taskc)
tasks.append(taskd)
tasks.append(taske)
#X = vectorizer.fit_transform(d[:96])
#on a 4 groupes et en chaque groupe groupe 5 etudiant A B C D E DONC
tab=[]
for k in range(5):
    print("#####result for task "+chr(ord('a')+k)+"##########")
    l=-1
    b=0
    tp={}
    for t in range(19):
        if t%5==0:
            b=0
            l+=1
        temp=[]
        temp.append(tasks[k][t])
        temp.append(task[k])
                #print(temp)
        X = vectorizer.fit_transform(temp)
        tp["Groupe "+str(l)+"e"+chr(ord('A')+b)+":"]=(euclidean_distances(X[0:1],X)[0,1])
        b+=1
    tab.append(tp)
    print(tp)


#####result for task a##########
{'Groupe 0eA:': 30.854497241083024, 'Groupe 0eB:': 35.11409973215888, 'Groupe 0eC:': 20.904544960366874, 'Groupe 0eD:': 15.556349186104045, 'Groupe 0eE:': 5.196152422706632, 'Groupe 1eA:': 25.748786379167466, 'Groupe 1eB:': 26.43860813280457, 'Groupe 1eC:': 18.0, 'Groupe 1eD:': 31.906112267087632, 'Groupe 1eE:': 33.04542328371661, 'Groupe 2eA:': 18.0, 'Groupe 2eB:': 14.142135623730951, 'Groupe 2eC:': 24.24871130596428, 'Groupe 2eD:': 27.0, 'Groupe 2eE:': 20.784609690826528, 'Groupe 3eA:': 29.086079144497972, 'Groupe 3eB:': 4.358898943540674, 'Groupe 3eC:': 19.72308292331602, 'Groupe 3eD:': 29.393876913398138}
#####result for task b##########
{'Groupe 0eA:': 39.26830783214372, 'Groupe 0eB:': 44.04543109109048, 'Groupe 0eC:': 51.07837115648854, 'Groupe 0eD:': 56.60388679233962, 'Groupe 0eE:': 57.59340239992772, 'Groupe 1eA:': 47.085029467974216, 'Groupe 1eB:': 46.42197755374064, 'Groupe 1eC:': 43.41658669218482, 'Groupe 1eD:': 35.93048844644336, 'Groupe 1

## en utilisant la méthode jaccard on a  

In [ ]:
def jaccard_similarity(query, document):
    intersection = set(query).intersection(set(document))
    union = set(query).union(set(document))
    return len(intersection)/len(union)
#jaccard_similarity(sent_tokenize(corpus[0]),sent_tokenize(corpus[95]))


In [13]:
def jaccard_similarity(doc1, doc2): 

    # Find the intersection of words list of doc1 & doc2
    intersection = set(doc1).intersection(set(doc2))

    # Find the union of words list of doc1 & doc2
    union = set(doc1).union(set(doc2))
        
    # Calculate Jaccard similarity score 
    # using length of intersection set divided by length of union set
    return float(len(intersection)) / len(union)

In [28]:
import pandas as pd
#vectorizer = CountVectorizer()
task=d[95:]
#print(task)
tasks=[]
tasks.append(d[:19])
tasks.append(d[19:38])
tasks.append(d[38:(38+19)])
tasks.append(d[(38+19):(38+2*19)])
tasks.append(d[(38+2*19):(38+3*19)])
#X = vectorizer.fit_transform(d[:96])
#on a 4 groupes et en chaque groupe groupe 5 etudiant A B C D E DONC
tab=[]
for k in range(5):
    print("#####result for task "+chr(ord('a')+k)+"##########")
    l=-1
    b=0
    tp={}
    for t in range(19):
        if t%5==0:
            b=0
            l+=1
        s1=tasks[k][t]
        s2=task[k]
        tp["Groupe "+str(l)+"e"+chr(ord('A')+b)+":"]=jaccard_similarity(s1,s2)
        b+=1
    tab.append(tp)
    print(tp)


#####result for task a##########
{'Groupe 0eA:': 0.0963855421686747, 'Groupe 0eB:': 0.05759162303664921, 'Groupe 0eC:': 0.07526881720430108, 'Groupe 0eD:': 0.042328042328042326, 'Groupe 0eE:': 0.06818181818181818, 'Groupe 1eA:': 0.12352941176470589, 'Groupe 1eB:': 0.055248618784530384, 'Groupe 1eC:': 0.05963302752293578, 'Groupe 1eD:': 0.08670520231213873, 'Groupe 1eE:': 0.05851063829787234, 'Groupe 2eA:': 0.22641509433962265, 'Groupe 2eB:': 0.04, 'Groupe 2eC:': 0.022727272727272728, 'Groupe 2eD:': 0.03333333333333333, 'Groupe 2eE:': 0.07514450867052024, 'Groupe 3eA:': 0.5564516129032258, 'Groupe 3eB:': 0.019230769230769232, 'Groupe 3eC:': 0.06321839080459771, 'Groupe 3eD:': 0.02142857142857143}
#####result for task b##########
{'Groupe 0eA:': 0.019230769230769232, 'Groupe 0eB:': 0.08461538461538462, 'Groupe 0eC:': 0.19889502762430938, 'Groupe 0eD:': 0.020942408376963352, 'Groupe 0eE:': 0.026455026455026454, 'Groupe 1eA:': 0.01932367149758454, 'Groupe 1eB:': 0.01809954751131222, 'Group

## 5.2 similarité semantique : Approche lexicale

In [1]:
from nltk.corpus import wordnet as wn 
computer_synsets = wn.synsets("computer") 
print("Computer sens in wordNet:")
i=0;
for sense in computer_synsets: 
    print(" \t Sens :", i)
    print(" \t\t Sens definition: "+sense.definition())
    lemmas = [l.name() for l in sense.lemmas()]
    print("\t\t Lemmas for sense :" +str(lemmas))
    i=i+1

Computer sens in wordNet:
 	 Sens : 0
 		 Sens definition: a machine for performing calculations automatically
		 Lemmas for sense :['computer', 'computing_machine', 'computing_device', 'data_processor', 'electronic_computer', 'information_processing_system']
 	 Sens : 1
 		 Sens definition: an expert at calculation (or at operating calculating machines)
		 Lemmas for sense :['calculator', 'reckoner', 'figurer', 'estimator', 'computer']


In [2]:
from nltk.corpus import wordnet as wn 
import pandas as pd
import numpy as np
computer_synsets = wn.synsets("computer") 
device_synsets = wn.synsets("study") 
lch=[]
wup=[]
print(device_synsets)

for s1 in computer_synsets:
    for s2 in device_synsets:
        lch.append(s1.path_similarity(s2))
        wup.append(s1.wup_similarity(s2))

#pd.DataFrame([lch,wup],["lch","wup"])


[Synset('survey.n.01'), Synset('study.n.02'), Synset('report.n.01'), Synset('study.n.04'), Synset('study.n.05'), Synset('discipline.n.01'), Synset('sketch.n.01'), Synset('cogitation.n.02'), Synset('study.n.09'), Synset('study.n.10'), Synset('analyze.v.01'), Synset('study.v.02'), Synset('study.v.03'), Synset('learn.v.04'), Synset('study.v.05'), Synset('study.v.06')]


In [3]:
from nltk.wsd import lesk
from nltk.tokenize import word_tokenize
def WSD(word, doc):
    context= word_tokenize(doc)
    sens=lesk(context, word)
    return sens

doc1='Computer science is the study of computers and computing concepts. It includes both hardware and software, as well as networking and the Internet'
doc2='Computer science is the science that deals with the theory and methods of processing information in digital computers, the design of computer hardware and software, and the applications of computers.'


print(WSD("Computer", doc1).definition())
print(WSD("Computer", doc2).definition())

a machine for performing calculations automatically
a machine for performing calculations automatically


**Defnir la fonction SemanticDistanceDocs(doc1,doc2) qui permet de calculer la distance semantique totale entre deux documents texte

## voici la fonction 

In [4]:
from nltk.corpus import wordnet as wn
from nltk.tokenize import word_tokenize

def SemanticDistanceDocs2(doc1,doc2):
    words=word_tokenize(doc1)
    ww=[word.lower() for word in words]
    wl= [word for word in ww if(not word in set(stopwords.words('english')) and  word.isalpha())]
    words=word_tokenize(doc2)
    ww=[word.lower() for word in words]
    wl2= [word for word in ww if(not word in set(stopwords.words('english')) and  word.isalpha())]
    s1=set(wl)
    s2=set(wl2)
    S=s1.union(s2)
    v1=[]
    v2=[]
    #print(S)
    #print(type(S))
    for i in S:
        if(i in s1):
            v1.append(1.0)
        else:
            syn1 = WSD(i,doc2)
            t=0.0
            for l in s1:
                temp=[]
                
                #print(l)
                syn2=WSD(l,doc1)
                if syn1 is not None and syn2 is not None:
                    
                    x=syn1.path_similarity(syn2)
                else:
                    x=0.0
                if x is not None:
                    if x>t:
                        t=x
                
            y=t
            #print(type(y))
            if y is not None:
                if y>0.25:
                    v1.append(y)
            else:
                v1.append(0)
    for i in S:
        if(i in s2):
            v2.append(1.0)
        else:
            syn1 = WSD(i,doc1) 
            for s in s2:
                temp=[]
                t=0.0
                syn2=WSD(l,doc2)
                if syn2 is not None and syn2 is not None:
                    
                    x=syn2.path_similarity(syn2)
                else:
                    x=0.0
                if x is not None:
                    if x>t:
                        t=x
                
            y=t
            #print(type(y))
            if y is not None:
                if y>0.25:
                    v2.append(y)
            else:
                v2.append(0)
    res=sum(i[0]*i[1] for i in zip(v1,v2))
    return res/len(S)
    
                        
                    
                
                
                
                
            

In [9]:
from nltk.corpus import wordnet as wn
from nltk.tokenize import word_tokenize

doc1='Computer science is the study of computers and computing concepts. It includes both hardware and software, as well as networking and the Internet'
doc2='Computer science is the science that deals with the theory and methods of processing information in digital computers, the design of computer hardware and software, and the applications of computers.'
doc1='Computer is the study of technology'
doc2='Computer is the study of intelligence'
#def SemanticDistanceDocs(doc1,doc2):
    
#print(SemanticDistanceDocs(doc1,doc2))
print(SemanticDistanceDocs2(doc1,doc2))

0.75


**Calculer les similarités syntaxiques entre les réponses des étudiants et les définitions trouvées sur wikipedia.

In [13]:
tasks=[]
tasks.append(taska)
tasks.append(taskb)
tasks.append(taskc)
tasks.append(taskd)
tasks.append(taske)
t=corpus[95:]

In [15]:
SemanticDistanceDocs2(tasks[2][0],t[2]) #exple d'application comparaison entre reponse du task c grp 0
#avec la vrai réponse

0.7772727272727272

In [ ]:
dict={}
tasks=[]
tasks.append(taska)
tasks.append(taskb)
tasks.append(taskc)
tasks.append(taskd)
tasks.append(taske)
t=corpus[95:]
for k in range(5):
    print("#####result for task "+chr(ord('a')+k)+"##########")
    l=-1
    b=0
    tp={}
    for t in range(19):
        if t%5==0:
            b=0
            l+=1
        tp["Groupe "+str(l)+"e"+chr(ord('A')+b)+":"]=SemanticDistanceDocs2(tasks[k][t],t[k])
        b+=1
    tab.append(tp)
    print(tp)
